echo:; Linear Units:
echo:  G21 ; (mm)
echo:; Temperature Units:
echo:  M149 C ; Units in Celsius
echo:; Filament settings (Disabled):
echo:  M200 S0 D1.75
echo:; Steps per unit:
echo:  M92 X80.00 Y80.00 Z800.00 E691.50
echo:; Max feedrates (units/s):
echo:  M203 X500.00 Y500.00 Z10.00 E30.00
echo:; Max Acceleration (units/s2):
echo:  M201 X500.00 Y500.00 Z100.00 E5000.00
echo:; Acceleration (units/s2) (P<print-accel> R<retract-accel> T<travel-accel>):
echo:  M204 P500.00 R500.00 T1000.00
echo:; Advanced (B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>):
echo:  M205 B20000.00 S0.00 T0.00 X8.00 Y8.00 Z0.40 E5.00
echo:; Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:; Auto Bed Leveling:
echo:  M420 S0 Z10.00 ; Leveling OFF
echo:; Material heatup parameters:
echo:  M145 S0 H185.00 B60.00 F255
echo:  M145 S1 H240.00 B80.00 F255
echo:; Hotend PID:
echo:  M301 P15.95 I1.30 D48.96
echo:; Bed PID:
echo:echo:  M304 P110.38 I6.12 D497.30
echo:; User thermistors:
echo:  M305 P0 R4700.0 T94162.0 B4160.0 C0.000000000 ; HOTEND 0
echo:; Power-loss recovery:
echo:  M413 S1 ; ON
echo:; Z-Probe Offset:
echo:  M851 X25.00 Y-25.00 Z0.00 ; (mm)
echo:; Stepper driver current:
echo:  M906 X860 Y900 Z800
echo:  M906 T0 E550
echo:; Hybrid Threshold:
echo:  M913 X183 Y183 Z41
echo:  M913 T0 E60
echo:; StallGuard threshold:
echo:  M914 X68 Y70
echo:; Driver stepping mode:
echo:  M569 S1 X Y Z
echo:  M569 S1 T0 E
echo:; Linear Advance:
echo:  M900 K0.04
echo:; Filament load/unload:
echo:  M603 L0.00 U50.00 ; (mm)